inherit: "dataset.yml"
version: "1.0.0"

# RSB
generative_backbone: "ncsnpp_base"
bridge_type: "VE"
training_method: "regularization"
training_target: "data"

# Shared optimization
learning_rate: 1.0e-4
batch_size: 16
patience: 20
predictive_patience: 50
mixed_precision: "none"
logger: "wandb"
seed: 10

num_epoch: 1000
ema_rate: 0.999
ema: True
optimizer: "Adam"
reduction: "sum"

# Regularized bridge objective
posterior_mean_from: "NCSN++M"
loss_weight_type: "constant"
regularization_weight: "quadratic"

t_min: 1.0e-4
t_max: 1
time_loss_weight: 1.0e-3

# Sampled validation metrics
valid_metric_samples: 50
test_metric_samples: 5
metric_num_steps: 20
